/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package godzina;

import javax.swing.DefaultListModel;

/**
 *
 * @author mateusz
 */
public class Godzina extends javax.swing.JFrame {

    /**
     * Creates new form Godzina
     */
    public Godzina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupRadio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        poleGodzina = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        guzikZeruj = new javax.swing.JButton();
        guzikWypisz = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        checkLetni = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        poleMinuta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        poleSekunda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        radioMinuty = new javax.swing.JRadioButton();
        radioGodziny = new javax.swing.JRadioButton();
        radioSekundy = new javax.swing.JRadioButton();
        guzikZmniejsz = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        guzikFormularz = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        poleWydarzenie = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaWydarzenia = new javax.swing.JList<>();
        guzikDodaj = new javax.swing.JButton();
        guzikWszystkie = new javax.swing.JButton();
        guzikKasuj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        poleGodzina.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel1.add(poleGodzina, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Godzina");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        guzikZeruj.setText("Zeruj");
        guzikZeruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikZerujActionPerformed(evt);
            }
        });
        jPanel1.add(guzikZeruj, java.awt.BorderLayout.PAGE_END);

        guzikWypisz.setText("Wypisz");
        guzikWypisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikWypiszActionPerformed(evt);
            }
        });
        jPanel1.add(guzikWypisz, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        checkLetni.setText("czas letni");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkLetni)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(checkLetni)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poleMinuta.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel2.add(poleMinuta);

        jLabel2.setText("Minut");
        jPanel2.add(jLabel2);

        poleSekunda.setPreferredSize(new java.awt.Dimension(150, 27));
        jPanel2.add(poleSekunda);

        jLabel3.setText("Sekund");
        jPanel2.add(jLabel3);

        getContentPane().add(jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new java.awt.BorderLayout());

        groupRadio.add(radioMinuty);
        radioMinuty.setText("minuty");
        jPanel4.add(radioMinuty, java.awt.BorderLayout.CENTER);

        groupRadio.add(radioGodziny);
        radioGodziny.setSelected(true);
        radioGodziny.setText("godziny");
        jPanel4.add(radioGodziny, java.awt.BorderLayout.PAGE_START);

        groupRadio.add(radioSekundy);
        radioSekundy.setText("sekundy");
        jPanel4.add(radioSekundy, java.awt.BorderLayout.PAGE_END);

        guzikZmniejsz.setText("Zmniejsz");
        guzikZmniejsz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikZmniejszActionPerformed(evt);
            }
        });
        jPanel4.add(guzikZmniejsz, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        guzikFormularz.setText("Formularz");
        guzikFormularz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikFormularzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guzikFormularz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(guzikFormularz)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        poleWydarzenie.setPreferredSize(new java.awt.Dimension(100, 27));

        jLabel4.setText("Wydarzenie");

        modelListy = new DefaultListModel<>();
        listaWydarzenia.setModel(modelListy);
        jScrollPane1.setViewportView(listaWydarzenia);

        guzikDodaj.setText("Dodaj");
        guzikDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikDodajActionPerformed(evt);
            }
        });

        guzikWszystkie.setText("Wszystkie");
        guzikWszystkie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikWszystkieActionPerformed(evt);
            }
        });

        guzikKasuj.setText("Kasuj");
        guzikKasuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guzikKasujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(poleWydarzenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(guzikWszystkie)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(guzikDodaj)
                        .addGap(18, 18, 18)
                        .addComponent(guzikKasuj)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(4, 4, 4)
                        .addComponent(poleWydarzenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guzikDodaj)
                            .addComponent(guzikKasuj))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guzikWszystkie)))
                .addContainerGap())
        );

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guzikZerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikZerujActionPerformed
        poleGodzina.setText("0");
    }//GEN-LAST:event_guzikZerujActionPerformed

    private void guzikWypiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikWypiszActionPerformed
        System.out.println(poleGodzina.getText());
    }//GEN-LAST:event_guzikWypiszActionPerformed

    private void guzikZmniejszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikZmniejszActionPerformed
        Integer godzina = Integer.valueOf(poleGodzina.getText());
        Integer minuta = Integer.valueOf(poleMinuta.getText());
        Integer sekunda = Integer.valueOf(poleSekunda.getText());
        
        if(radioGodziny.isSelected())  godzina -= 1;
        if(radioMinuty.isSelected()){
            if(minuta == 1){
                minuta = 59;
                poleMinuta.setText(minuta.toString());
                godzina -= 1;
            }
            else minuta -= 1;
        }
        if(radioSekundy.isSelected()){
            if(sekunda == 1){
                sekunda = 59;
                poleSekunda.setText(sekunda.toString());
                minuta -= 1;
            }
            else    sekunda -= 1;
        }
        
        poleGodzina.setText(godzina.toString());
        poleMinuta.setText(minuta.toString());
        poleSekunda.setText(sekunda.toString());
    }//GEN-LAST:event_guzikZmniejszActionPerformed

    private void guzikFormularzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikFormularzActionPerformed
        String godzina = poleGodzina.getText();
        String minuta = poleMinuta.getText();
        String sekunda = poleSekunda.getText();
        
        if(Integer.valueOf(godzina) < 10) godzina = "0" + godzina;
        if(Integer.valueOf(minuta) < 10) minuta = "0" + minuta;
        if(Integer.valueOf(sekunda) < 10) sekunda = "0" + sekunda;
        
        System.out.println(godzina+":"+minuta+":"+sekunda);
    }//GEN-LAST:event_guzikFormularzActionPerformed

    private void guzikDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikDodajActionPerformed
        String godzina = poleGodzina.getText();
        String minuta = poleMinuta.getText();
        String sekunda = poleSekunda.getText();
        String wydarzenie = poleWydarzenie.getText();

        String opis = wydarzenie + " "+ godzina + " " + minuta + " " + sekunda;
        
        if(Integer.valueOf(godzina) < 10) godzina = "0" + godzina;
        if(Integer.valueOf(minuta) < 10) minuta = "0" + minuta;
        if(Integer.valueOf(sekunda) < 10) sekunda = "0" + sekunda;
        
        modelListy.addElement(opis);
    }//GEN-LAST:event_guzikDodajActionPerformed

    private void guzikWszystkieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikWszystkieActionPerformed
        for(int i =0; i < modelListy.size(); i++)
            System.out.println(modelListy.elementAt(i));
    }//GEN-LAST:event_guzikWszystkieActionPerformed

    private void guzikKasujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guzikKasujActionPerformed
        modelListy.removeAllElements();
    }//GEN-LAST:event_guzikKasujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Godzina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Godzina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Godzina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Godzina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Godzina().setVisible(true);
            }
        });
    }
    private DefaultListModel<String> modelListy;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkLetni;
    private javax.swing.ButtonGroup groupRadio;
    private javax.swing.JButton guzikDodaj;
    private javax.swing.JButton guzikFormularz;
    private javax.swing.JButton guzikKasuj;
    private javax.swing.JButton guzikWszystkie;
    private javax.swing.JButton guzikWypisz;
    private javax.swing.JButton guzikZeruj;
    private javax.swing.JButton guzikZmniejsz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaWydarzenia;
    private javax.swing.JTextField poleGodzina;
    private javax.swing.JTextField poleMinuta;
    private javax.swing.JTextField poleSekunda;
    private javax.swing.JTextField poleWydarzenie;
    private javax.swing.JRadioButton radioGodziny;
    private javax.swing.JRadioButton radioMinuty;
    private javax.swing.JRadioButton radioSekundy;
    // End of variables declaration//GEN-END:variables
}
